import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
// import Providers from "./Providers";
import { Provider } from "./utils/Provider";
import { Sidebar } from "./_components/Sidebar";
import SidebarProvider from "./_components/SidebarContext";
import { Header } from "./_components/Header";
//src/app/utils/Providers.tsx

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const setInitialTheme = `
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
        
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" suppressHydrationWarning>
    <html lang="en">
      <Head>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
      </Head>
      <body className={`${inter.className} layout`}>
        <SidebarProvider>
          <Sidebar></Sidebar>
          <Header></Header>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
